authors:
  dataguirre:
    name: Daniel Aguirre
    description: Senior Associate
    url: https://github.com/dataguirre
    avatar: assets/authors/dataguirre.jpeg
  carlos-toruno:
    name: Carlos A. Toruño P.
    description: WJP team
    url: https://www.carlos-toruno.com/
    avatar: https://github.com/ctoruno.png
