authors:
  dataguirre:
    name: Daniel Aguirre
    description: Senior Associate
    url: https://github.com/dataguirre
    avatar: https://media.licdn.com/dms/image/v2/D4E03AQHUh6rmDfaeug/profile-displayphoto-crop_800_800/B4EZ4..W.QJMAQ-/0/1779172995694?e=1781136000&v=beta&t=SAVYpE2IjYIQrBaLK262QNorBfrnlZKG0iHAWhnT4bc
